[default]
background = "#000066"
separator_block_width = 16
border = "#00aa00"

[[bar]]
widget = "brightness"
border = "#00aa00"

[[bar]]
widget = "battery"
border = "#00aa00"

[[bar]]
widget = "window_name"
align = "left"
min_width = 1321
width = 80

[[bar]]
widget = "volume"
align = "center"

[[bar]]
widget = "time"
align = "right"
format = "%b %d %A %l:%M:%S %p"
