[package]
name = "barnine"
version = "0.1.0"
authors = ["Zach Thompson <zach@allotropic.com>"]
edition = "2018"
default-run = "barnine"

[dependencies]
allotropic = { path = "../allotropic" }
async-std = "1.9.0"
chrono = "0.4.19"
futures-lite = "1.11.3"
lazy_static = "1.4.0"
log = "0.4.13"
serde_json = "1.0.61"
smol = "1.2.5" 
swaybar-types = "2.0.0"
swayipc-async = "2.0.0-alpha.2"
zbus = { path = "../../src/zbus-async-proxy/zbus" } # "2.0.0-beta"
zbus_macros = { path = "../../src/zbus-async-proxy/zbus_macros" } # "2.0.0-beta"
zvariant = { path = "../../src/zbus-async-proxy/zvariant" } # "2.0.5"
