[package]
name = "barnine"
version = "0.1.0"
authors = ["Zach Thompson <zach@allotropic.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
allotropic = { path = "../allotropic" }
async-std = "1.9.0"
chrono = "0.4.19"
log = "0.4.13"
serde_json = "1.0.61"
smol = "1.2.5" 
swaybar-types = "2.0.0"
swayipc-async = "2.0.0-alpha.2"
